# Generated by Django 4.0.6 on 2022-08-08 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='menu_image',
        ),
        migrations.RemoveField(
            model_name='review',
            name='parent',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='openning_times',
            field=models.CharField(max_length=255, verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Отзыв', to='rest.review', verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest.sale', verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='selections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest.selection', verbose_name='Подборка'),
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_restaurant/', verbose_name='Изображения')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Фото', to='rest.restaurant', verbose_name='Фото')),
            ],
        ),
    ]
